<?php
/**
 * Build-plan view. When a session is complete, the right panel transitions from
 * the domain matrix to this view.
 *
 * The 5 prompt SECTIONS are the agreed structure (Big Picture Plan §3c). The prompt
 * CONTENT is produced by the Compiler Agent (ManifestGenerator, FP9), stored on the
 * session as an ordered array of 5 strings. Each prompt renders in a monospace block
 * with a copy button; the whole plan can be downloaded as .md or .txt.
 *
 * Expects $session in scope (included from session.php).
 */
$planSections = [
    ['Project Initialization', 'Paste this first:'],
    ['Data Layer',             'Paste this after Prompt 1 is confirmed:'],
    ['Core Feature Build',     'Paste this after the schema is confirmed:'],
    ['UI Construction',        'Paste this after the core logic is confirmed:'],
    ['Integration & Testing',  'Paste this last:'],
];
$builtPlan = $session['build_plan'] ?? null;   // ordered [p1..p5], populated at FP9
?>
<style>
    /* ── Build-plan panel (FP9) ─────────────────────────────────── */
    .plan-step {
        width: 1.7rem; height: 1.7rem; border-radius: 50%;
        background: #198754; color: #fff; font-size: .82rem; font-weight: 700;
        display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0;
    }
    .plan-prompt {
        background: #f8f9fa; border: 1px solid #e9ecef; border-radius: .45rem;
        padding: .65rem .8rem; margin: 0 0 .6rem; font-size: .8rem; line-height: 1.5;
        white-space: pre-wrap; word-break: break-word;
        font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    }
    .copy-prompt-btn { border-width: 2px; letter-spacing: .01em; }
    .copy-prompt-btn.copied { background: #198754; border-color: #198754; color: #fff; }
    .plan-header { background: #d1e7dd; border: 1px solid #badbcc; color: #0f5132; }
</style>

<div class="p-3 p-md-4 build-plan">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2 class="h6 text-uppercase text-muted mb-0">Your Build Plan</h2>
        <span class="badge bg-success rounded-pill">8/8 ✓</span>
    </div>

    <div class="plan-header rounded p-3 mb-3 small">
        All 8 domains covered. Paste these into Claude Code, ChatGPT, or Gemini
        <strong>in order</strong> — confirm each step before moving to the next.
    </div>

    <?php foreach ($planSections as $i => [$name, $paste]): ?>
        <?php $content = $builtPlan[$i] ?? ''; ?>
        <div class="card mb-3 plan-card">
            <div class="card-body p-3">
                <div class="d-flex align-items-center gap-2 mb-1">
                    <span class="plan-step"><?= $i + 1 ?></span>
                    <span class="fw-semibold text-uppercase small"><?= htmlspecialchars($name) ?></span>
                </div>
                <div class="text-muted mb-2" style="font-size:.78rem;"><?= htmlspecialchars($paste) ?></div>
                <?php if ($content !== ''): ?>
                    <pre class="plan-prompt"><?= htmlspecialchars($content) ?></pre>
                    <button type="button" class="btn btn-outline-primary btn-sm w-100 fw-semibold copy-prompt-btn"
                            data-prompt-index="<?= $i ?>">
                        &#9106;&nbsp; Copy Prompt <?= $i + 1 ?>
                    </button>
                <?php else: ?>
                    <div class="text-muted small">Generated by the Compiler Agent.</div>
                <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>

    <?php if ($builtPlan): ?>
        <div class="row g-2 mt-1">
            <div class="col-6">
                <button type="button" class="btn btn-outline-secondary w-100 download-btn" data-format="md">Download .md</button>
            </div>
            <div class="col-6">
                <button type="button" class="btn btn-outline-secondary w-100 download-btn" data-format="txt">Download .txt</button>
            </div>
        </div>
    <?php endif; ?>
</div>

<?php if ($builtPlan): ?>
<script>
    // Compiler Agent output (FP9): copy a single prompt, or download the whole plan.
    (function () {
        var prompts  = <?= json_encode(array_values($builtPlan), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?>;
        var sections = <?= json_encode(array_map(fn($s) => $s[0], $planSections), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?>;

        function copyText(text, onDone) {
            if (navigator.clipboard && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(text).then(onDone).catch(onDone);
            } else {
                var ta = document.createElement('textarea');
                ta.value = text; document.body.appendChild(ta); ta.select();
                try { document.execCommand('copy'); } catch (e) {}
                document.body.removeChild(ta); onDone();
            }
        }

        document.querySelectorAll('.copy-prompt-btn').forEach(function (btn) {
            btn.addEventListener('click', function () {
                var idx = parseInt(btn.getAttribute('data-prompt-index'), 10);
                copyText(prompts[idx] || '', function () {
                    var original = btn.innerHTML;
                    btn.classList.add('copied');
                    btn.innerHTML = 'Copied &#10003;';
                    setTimeout(function () { btn.classList.remove('copied'); btn.innerHTML = original; }, 1500);
                });
            });
        });

        // Assemble the full plan in the requested format and trigger a download.
        function buildPlanText(format) {
            var out = [];
            if (format === 'md') {
                out.push('# Your Software Build Plan', '', '_Generated by Requirement Orchestrator_', '');
                prompts.forEach(function (p, i) {
                    out.push('## Prompt ' + (i + 1) + ' — ' + sections[i], '', '```', p, '```', '');
                });
            } else {
                out.push('YOUR SOFTWARE BUILD PLAN', 'Generated by Requirement Orchestrator', '');
                prompts.forEach(function (p, i) {
                    out.push('PROMPT ' + (i + 1) + ' — ' + sections[i].toUpperCase(),
                             '------------------------------------------------------------', p, '');
                });
            }
            return out.join('\n');
        }

        document.querySelectorAll('.download-btn').forEach(function (btn) {
            btn.addEventListener('click', function () {
                var format = btn.getAttribute('data-format');
                var blob = new Blob([buildPlanText(format)],
                    { type: format === 'md' ? 'text/markdown' : 'text/plain' });
                var url = URL.createObjectURL(blob);
                var a = document.createElement('a');
                a.href = url; a.download = 'build-plan.' + format;
                document.body.appendChild(a); a.click(); document.body.removeChild(a);
                URL.revokeObjectURL(url);
            });
        });
    })();
</script>
<?php endif; ?>
