<?php
/**
 * Build-plan view (FP6 placeholder). When a session is complete, the right
 * panel transitions from the domain matrix to this view.
 *
 * The 5 prompt SECTIONS are the agreed structure (Big Picture Plan §3c). The
 * actual prompt CONTENT is generated by the Compiler Agent (ManifestGenerator,
 * FP9) — until then this shows the structure and a disabled copy button.
 *
 * Expects $session in scope (included from session.php).
 */
$planSections = [
    'Project Initialization',
    'Data Layer',
    'Core Feature Build',
    'UI Construction',
    'Integration & Testing',
];
$builtPlan = $session['build_plan'] ?? null;   // populated at FP9
?>
<div class="p-3 p-md-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2 class="h6 text-uppercase text-muted mb-0">Your Build Plan</h2>
        <span class="badge bg-success rounded-pill">8/8 ✓</span>
    </div>

    <div class="alert alert-success py-2 small" role="alert">
        All 8 domains covered. Your sequenced 5-prompt build plan goes here.
    </div>

    <?php foreach ($planSections as $i => $name): ?>
        <div class="card mb-2">
            <div class="card-body py-2 px-3">
                <div class="fw-semibold small">PROMPT <?= $i + 1 ?> — <?= htmlspecialchars(strtoupper($name)) ?></div>
                <div class="text-muted small">
                    <?= $builtPlan
                        ? nl2br(htmlspecialchars($builtPlan[$i] ?? ''))
                        : 'Generated by the Compiler Agent (FP9).' ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>

    <button class="btn btn-outline-secondary btn-sm w-100 mt-2" type="button" disabled>
        Copy Prompt 1 &nbsp;(enabled at FP9)
    </button>
</div>
